services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: narou_analyzer:latest
    env_file:
      - .env
    environment:
      NAROU_URL: ${NAROU_URL:-https://api.syosetu.com/}
